### ISSUE TITLE
Make massa-sc-toolkit Release-Ready 

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/massa-sc-toolkit#154]
# Objective
The purpose of this issue is to ensure that the library is updated to meet the expected criteria for an application to be maintained and considered release-ready. The requirements are outlined in the Run team procedure: [Definition of Release-Ready](https://www.notion.so/massa-innoteam/Definition-of-Release-Ready-964a4f2ffd9549129edf76d6c623c490).

# Tasks
This issue is a meta issue. Please create additional issues to perform the task and reference them. Keep in mind that the issues should be as short as possible to improve overall efficiency.

### Code documentation

**Document deployer**
- [x] #160

**Document initializer**
- [x] #162
- [x] #164
- [x] #168

** Document massa-proto-cli**

### Git Documentation
**massa-sc-toolkit root**
- [x] #184
- [x] #182
- [x] #180
- [ ] Update or improve Readme

**sc-deployer**
- [x] #169
- [x] #170
- [x] #171
- [x] #186

**sc-project-initializer**
- [x] #176
- [x] #177
- [x] #174
- [x] #187

**massa-proto-cli**
- [x] #281
- [x] #285
- [x] #283
- [x] #261
- [x] #275 

## Testing
- [ ] #191
- [ ] Add coverage badge
- [ ] Improve test coverage
- [x] #206

**Test deployer**
- [x] #213
- [ ] test awaitOperationFinalization from sc-deployer/src/index.ts
- [ ] test pollAsyncEvents from sc-deployer/src/index.ts
- [ ] test deploySC from sc-deployer/src/index.ts
- [ ] #205

**Test massa-proto-cli**
- [x] #269
- [x] #271
- [ ] test ts-gen.ts

## Security

- [ ]  Define a security model
- [ ]  Implement proper countermeasures, such as static analysis of code and security checks of dependencies

## Automation
- [ ]  Automate tasks that can be automated

## Compatibility
- [x] #183

## Wrap Up

- [ ]  Ensure that the Run team procedure was properly applied and update the document if necessary
- [ ]  Communicate that the library is now considered release-ready
