### ISSUE TITLE
What's missing for the transformers and the proto-cli to be ready ?

### ISSUE THREAD

**Issue by Elli610** [massalabs/massa-sc-toolkit#289]
You will find below a non-exhaustive list of the tasks to be accomplished so that as-transformers and massa-proto-cli are perfectly functional.

### as-transformer

Ongoing:
- [x] Generate a templated event with the return value of massa exported (transformed) functions
#### handle non-native types: https://github.com/massalabs/as/issues/277
- [x] handle non-native types yml configuration files
- [x] generate proto files using yml config files
- [x] generate helpers using the new proto files
- [x] generate sc function wrappers using config files and new helpers
- [ ] Write yml config files for types described in as-types
- [ ] handle custom types arrays
- [x] #325

Todo:
- [x] Transfer knowledge
- [ ] Ensure code readibility and test coverage
- [ ] Documentation (repo + docu-dev)
- [ ] Upgrade standards and examples

### massa-proto-cli

Ongoing:
- [x] #323
#### handle non-native types
- [x] #317
- [x] #328
- [x] Add custom type args to cli proto structure
- [x] Add custom type return to cli proto structure
- [x] #334
- [x] Generate AS helpers using new proto file
- [x] #335
- [x] Add custom type args serialization in AS callers
- [x] #336
- [x] Add custom type return deserialization in AS callers
- [x] #339
- [x] Add custom type imports in AS callers
- [x] #340
- [ ] Handle custom types array in the as callers
- [ ] caller ts: auto convert u128 and u256 to bigint 

Todo:
- [x] Do not hard code the node address to use for ts callers. Instead, ask the for the dev to set it up using that of the provider (web3 or wallet-provider)
- [x] #322
- [x] #326
- [ ] Handle arrays as argument and output in the as callers

To be checked
- [ ] Check if when a function of SC calls calls another, we have 2 events which contain "Result: ". If so, modify ts-gen to get the correct one and delete the others. (must be done once events containing function outputs have been implemented)
- [ ] For each native type, check the overflows between types as and their equivalents ts. If there may be any, add the necessary conditions at the beginning of the caller

### as-transformer
To be completed if needed

### massa-proto-cli
- [ ] Handle the case where from several addresses we generate caller files with the same name ->  we should put them in folders whose name are the addresses of the contracts
- [ ] Add documentation for the generated as callers
- [x] #330
- [x] #347
- [ ] add a command to generate callers from local proto files
- [x] #315
